### ISSUE TITLE
error on php 5.6.x

### ISSUE THREAD

**Issue by simonpeters** [Rareloop/wp-router#1]
got this error

````
Parse error: syntax error, unexpected ':', expecting ';' or '{' in path/to/project/web/app/plugins/wp-router/src/Router.php on line 80
--
````

using php 5.6.28

**Comment by adamtomat** [comment]
Unfortunately we are currently only supporting PHP 7+.

The error you are getting is because this package is using some PHP 7 features, such as: return types, scalar typehinting and the null coalesce operator (`??`).
